const mongoose=require('mongoose')
const uuidv1=require('uuidv1')
const crypto=require('crypto')
const { type } = require('os')

const userSchema=new mongoose.Schema({
    name:{
        type:String,
        require:true,
        trim:true
    },
    email:{
        type:String,
        require:true,
        trim:true,
        unique:true
    },
    role:{
        type:Number,
        default:0
    },
    hashed_password:{
        type:String,
        require:true
    },
    salt:String,     //salt is use to store value generated by uuid
    isVerified:{
        type:Boolean,
        default:false
    }
},{timestamps:true})

// virtual fields
userSchema.virtual('password')
.set(function(password){
    this._password=password
    this.salt=uuidv1()
    this.hashed_password=this.encryptPassword(password)
})
.get(function(){
    return this._password
})

// defining methods
 userSchema.methods={
    encryptPassword:function(password){
        if(!password) return''
        try{
            return crypto
            .Hmac('sha1',this.salt) //Hmac is encryption algorithm of crypto
            .update(password)
            .digest('hex')
        }
        catch(err){
            return err
        }
    },
    authenticate:function(plainText){
        return this.encryptPassword(plainText)===this.hashed_password
    }
 }


module.exports=mongoose.model('User',userSchema)